language: python

matrix:
  include:
    - python: 2.7
      env: TOXENV=python2.7
    - python: 3.3
      env: TOXENV=python3.3
    - python: 3.4
      env: TOXENV=python3.4
    - python: 3.5
      env: TOXENV=python3.5

os:
  - linux

install:
  - pip install tox
  - pip install coveralls

script: 
  - tox
  - python setup.py test --addopts "-v --cov pytablereader --cov-report term-missing"

after_success:
  - coveralls

notifications:
  slack:
    secure: tXJkXdgb7bzpSJEginNBL3Q+XUeJ31D2wlRhhPGm4TN0EtlO6oAWkDZVEfzssE1aQtYXXotfa5xFIaLOlR+bDT9JVjAkmEcWZPNwCs7GiRgTEvVFMYtbaf8tgN0eLXxKmxGiWQLTa+0hF06GkOh6sxfrTGT7gMJCSXV786wTFQrMRzgrc4dgOX3HWo0xx3Ffuu99uud2ucmX5ZWzha8DOac/ka83pL0XbzCnkdMHD8rARa1KKzlciIM6aU9k7yHOKd869ZkG2X2bw05CWWDgNzjYXtjqeOtGjskmtKQOcD2vav2EHBw8yzIkyZv7mWFehrE1qRDCAFHd2xOv+6GGkinF5Wjp3hpZjsBhtt/6IPp1sQM1zAD+A8p3XGH+H7CUSe32CpgmbQ6bei5np6MXE5hjO5bcrJHDzmuAOMcxiIWpwp5aYA4hgb81Dv94LC1UdCk+gh9KomCJVCN4yttwsv790AXcasbgo5kA2syRE0XToczKDpqSeKdDrrXcNu+RkYeVTjkrfBPte0RWtUnfE3txWU6kHtHWWOGYMr9M8sNsDuX2CqDLAw5UPPGCaybBpdo6etsf7vcxncz7fp+CKpLXjl3iykqzthCY9rqmfdmwwHqdYLB2ybZUyGPs8nnkE/rY904/3t7v6N1OAfbwQ5WNuHAJbDn4cZ64HhH8pOM=